import "./globals.css";

export const metadata = {
  title: "Estudo Next.JS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <h1>Teste</h1>
      <body>{children}</body>
    </html>
  );
}
